### PR TITLE
fix(@cubejs-client/core): incorrect types for logical and/or in query filters (#3083)

### PR DESCRIPTION
**Pull request by rdwoodring**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet (n/a - change updates index.d.ts
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**
#3083

**Description of Changes Made (if issue reference is not provided)**
Update index.d.ts so that filter field in Query supports logical and/or in TypeScript.

### CODE REVIEW

**Review by hassankhan — APPROVED** [review]

**Comment by hassankhan** [comment]
Nice job @rdwoodring 🙌 

/cc @vasilev-alex

**Comment by rdwoodring** [comment]
@hassankhan Thanks.

Sadly, it seems this PR broke the build in query-builder. I think implementing and/or filters in the query builder is probably outside the scope of this PR, but I can go back and revise it to fix query builder's types for now so the build passes.

**Comment by vasilev-alex** [comment]
@rdwoodring exactly. Let me know if you're working on the fix otherwise, I'll fix the query builder myself

**Comment by rdwoodring** [comment]
@vasilev-alex I should be able to have a go at fixing it this evening

**Comment by rdwoodring** [comment]
@vasilev-alex updated query-builder/query-members.ts. 🤞 that the build passes

**Pull request merged**
