### PR TITLE
[WIP] @cubejs-backend/server-test

### LINKED ISSUE #129: Testing?
**Is your feature request related to a problem? Please describe.**
I'm currently setting up a TDD flow for cubejs. I have two questions:

1. What would one test with regards to cubejs? So far on my side I think that testing the schemas for proper output seems to be a good rule of thumb.
2. Is there already a mechanism integrated to cubejs for testing?

**Describe the solution you'd like**
Cubejs provides an npm command that allows to run test against a mock database. Doesn't require extra setup bar installing dependencies (and potentially having docker/docker-compose) installed.

**Describe alternatives you've considered**
I've implemented a docker-compose setup with jest for integration testing (e2e). It runs cube in its own docker environment and uses jest to fill the database, issue queries using `@cubejs-frontend/core`, and test the result. Now I was wondering if there would be a way for such flow to be either done without a database, or done similarly, but without the need for extra setup like I did.

**Additional context**
If you are interested I can share my test setup repository :)

### PR DESCRIPTION
**Pull request by philippefutureboy**
# Description

Cube.js currently does not have an easy workflow for testing and requires the users to setup their own testing workflow over Cube.js in order to ensure that the schemas answer the requirements successfully.

This PR's goal is to create a test harness package for Cube.js under the `@cubejs-backend/server-test` package name.

Fixes #129

**User stories**:

* As a software engineer using Cube.js, I want to test my schemas as part of my development workflow using tooling provided out of the box by Cube.js
* As a software engineer using Cube.js, I want to test my schemas using the testing framework of my choice. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Roadmap

- [x] Establish requirements
- [ ] Establish architecture & necessary changes to other packages
- [ ] Implementation [TBD]

# Testing

**Test Configuration**:
* Node.js v8.11.1
* npm v6.9.0
* jest 24.8.0

**Tests**:

[TBD]

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the conventional commits format
- [ ] I have reviewed my commit history using `git rebase -i` and removed any unnecessary commits through `fixup` or squashing
- [ ] My styling follows the style guide of the repository
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes do not generate new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My dependencies are free of vulnerabilities

### CODE REVIEW

**Comment by philippefutureboy** [comment]
# Requirements

## Skeleton

* Support all of the normal properties of CubejsServer.create config
* Implement all of the normal CubejsServer API
* Implement a supplementary API for preparing fixtures & teardown
* Implement necessary API to run query.

## Muscles

* Support multitenancy

## Skin

* Efficiency in docker resource usage
* Optimization of test time

**Comment by philippefutureboy** [comment]
# Architecture & Necessary Changes to Existing Codebase

**Comment by philippefutureboy** [comment]
# Tests

[TBD]

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! That's a huge one! Thanks for providing this! Could you please provide some examples on how to use it so I can get a sense on how to review this?

**Comment by philippefutureboy** [comment]
@paveltiunov Thanks a lot :))
You'll find an example usage of CubejsTest below. It is still unclear to me whether or not the dbType & driver require the query as part of their context when [the function executes](https://github.com/cube-js/cube.js/blob/1c2083841c3a304112c26cd6784fce255423249f/packages/cubejs-server-core/core/index.js#L208). If it is the case, then the API has to be revised so that the 

### 1. Initialization:

```
const cubejsTest = new CubejsTest({
  // various common params for CubejsServerCore goes here like driverFactory if required
  // based on a driver provided appropriate DB container should be started
});
```

### 2. Preparing fixtures:

Preparing fixtures should be test-bound, in case tests require conflicting database state.
Each test should have its own database schema within the container instance, whenever possible. 

Here are two possible APIs:

**Vanilla:**

```js
// arrange
const fixtures = '...'
const databaseID = await cubejsTest.createDatabase();
await cubejsTest.prepareFixtures(databaseID, fixtures);
// act
const result = await cubejsTest.runQuery(databaseID, { ... });
// assert
...
// clean
cubejsTest.dropDatabase(databaseID);
```

* The user never directly executes SQL against the database. The CubejsTest instance is responsible for that.
* databaseID is an ID provided by cubejsTest rather than the name of an actual database.

**Context requires query**:

```js
// arrange
const fixtures = '...'
const databaseID = cubejsTest.createDatabase();
cubejsTest.prepareFixtures(databaseID, fixtures);
// act
const result = await cubejsTest.runQuery(databaseID, { ... });
// assert
...
// clean
await cubejsTest.dropDatabase(databaseID);
```

* databaseID is an ID provided by cubejsTest rather than the name of an actual database.
* The database is not created until the runQuery call is run. Fixtures are stored in a data structure inside of the cubejsTest instance which retrieves and executes the fixtures the first time the runQuery is called.
* `createDatabase` and `prepareFixtures` are synchronous, but could be wrapped in a Promise to match users' expectation that it is async (and potentially futureproof the API).

### 3. Tear down

```js
afterAll(() => cubejsTest.tearDown())
```

* It actually won't be necessary as the ContainerOrchestrator will automatically tear down any resource associated with a process that shut down, since it will rely on a websocket connection to establish if the process is still up or not. It may still be useful for future cleanup, so we may want to leave it there as a way to futureproof the API, even if potentially a noop at first.

There you go 🎉

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Could you please forward me to file where `CubejsTest` resides?

**Comment by philippefutureboy** [comment]
@paveltiunov It is currently not implemented, it is a work in progress ;)
You'll find the package folder for CubejsTest [here](https://github.com/arthurintelligence/cube.js/tree/feat/cubejs-server-test/packages/cubejs-server-test).

**Comment by paveltiunov** [comment]
@philippefutureboy I see. Cool! Looking forward to it!

**Comment by philippefutureboy** [comment]
Don't be too disappointed, it's coming XP

**Comment by paveltiunov** [comment]
@philippefutureboy Yeah. No worries. I just saw decent change set and thought it's already there. 👍

**Comment by philippefutureboy** [comment]
## Update

### Progress (this weekend)

Done
- Container-orchestrator should ensure that it has the necessary tools at hand to work.
- Only one container-orchestrator per repository should run at any one moment.

In Progress
- The Container-orchestrator is responsible for orchestrating the docker container and provide info about how to connect to them.
- Container-orchestrator should tear down all resources when they are no longer needed.

### Learnings

* The container orchestrator should handle container name collisions
* The container orchestrator should keep the images after shutdown
* The container orchestrator should check which containers need to stay up based on who asked for it
* The container orchestrator should retain the credentials necessary to access the databases
* Some databases won't be dockerizable, like Athena. So it would be important to still allow the user to do tests against a real, hosted db. In such cases, the container orchestrator should completely be bypassed.
* In some cases, the currently planned multiple-schema multitenancy (one schema per test file/per unit test) may not be possible for all database types. As such, multitenancy should be handled at the driver level rather than by CubejsTest.


### Architectural Changes to packages that will be necessary for this to work

* The drivers should all respect the same interface and behave in the same way. More specifically, the connection should be done after the constructor, so that the configuration can be instrumented by CubejsTest

### Updated Future Interface

```js
  new CubejsTest({
   dbType: () => ...
   driverFactory: () => new MySQLDriver({
     host: ''
     database: ''
     port: ''
     user: ''
     password: ''
   }),
   contextToAppId: () => {}
   containerFactory: (context, dbType, driverFactory) => ({
     overrideContainerOrchestrator: false, // defaults to CUBE_JS_TEST_OVERRIDE_ORCHESTRATOR || false
     image: 'mysql:5.7', // defaults to the image specified by the driver
     name: 'my-mysql', // defaults to cubejs_${app name || repository folder name }_${ hash of image + env }
     env: { // defaults to the env specified by the driver
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
     },
   }),
  })
```

On a final note, I realized I don't have the necessary knowledge to implement the dockerization of all of the database solutions. As such my suggestion is that I start by supporting a few databases, such as `postgres` and `mysql`, and then later improve the support as more requests & PRs come in.

That's it for today!
If you have any questions, let me know :)

**Comment by rpaik** [comment]
@philippefutureboy and @paveltiunov I was just going through old issues/PRs. Is this still being worked on? If not, can we close this?

**Comment by philippefutureboy** [comment]
@rpaik Hey Ray!

No unfortunately due to the lack of time and the enormous size of the endeavour I cannot follow-through with this one.
With more experience under my belt, I'm not even sure that this is something that Cube.js should endeavour to do, at least not as part of Cube's core offering.

To me, this feels more like a generic data engineering issue rather than a Cube.js specific issue.
Up to @paveltiunov if he thinks this can be part of Cube.js' strategy.

**Comment by hassankhan** [comment]
@philippefutureboy It was indeed a massive endeavour 😄 I still think there are things that we can take away from this PR, even if it isn't merged. In particular, changing drivers such that async connection establishment happens separately from driver construction is something I think would benefit all drivers in that we wouldn't have to awkwardly hold references to promises and later execute them.

**Comment by rpaik** [comment]
How about if we just close this PR for now? We can always reopen or start with new PR(s).

**Pull request closed without merging**
