### PR TITLE
feat(dreamio-driver): Improve polling, similar to BigQuery driver

### PR DESCRIPTION
**Pull request by rongfengliang**
query  with sleep for 1s is too long ,  maybe needless  (we can use dremio `Data Reflections` for accelerate data query  )

### CODE REVIEW

**Comment by paveltiunov** [comment]
Hey @rongfengliang ! We can use linear backoff like in the BigQuery driver here however without a timer it'll burst dremio concurrency pretty fast.

**Comment by rongfengliang** [comment]
> Hey @rongfengliang ! We can use linear backoff like in the BigQuery driver here however without a timer it'll burst dremio concurrency pretty fast.

i agreen, i will try do some change  like    BigQuery  driver

**Comment by rongfengliang** [comment]
@paveltiunov  i have do some   change  like bigquery driver (response  is fast than before) , config just like bigquery driver

```code
CUBEJS_DB_POLL_TIMEOUT
CUBEJS_DB_POLL_MAX_INTERVAL
```

**Comment by rongfengliang** [comment]
@paveltiunov thanks

**Comment by ovr** [comment]
Thank you @rongfengliang 🍰 👍

**Pull request merged**
