### PR TITLE
Added boolean filters to Filter typings

### PR DESCRIPTION
**Pull request by thetylerwolf**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

Resolves the issue of boolean filters not existing on client-core typings (not in issues) - #259 

**Description of Changes Made (if issue reference is not provided)**

Added typings for "and" and "or" logic on binary and unary filters

### CODE REVIEW

**Review by vasilev-alex — APPROVED** [review]

**Comment by Manny91** [comment]
Hello, 
I was just wondering when the boolean operators in filters ( ```and``` or ```or```) is this going to be released?

**Comment by thetylerwolf** [comment]
The boolean filters are already available in cube since at least v0.21.1. This PR was to add their typings to the cube client library. If you're trying to use the boolean operators in a filter, make sure you've updated both your cube client libraries and the cube server library.

**Comment by Manny91** [comment]
Hi @thetylerwolf, thanks for your response, I've seen this is been merged into master but when I go to https://github.com/cube-js/cube.js/blob/v0.21.2/packages/cubejs-client-core/index.d.ts 
and 
https://github.com/cube-js/cube.js/blob/v0.21.1/packages/cubejs-client-core/index.d.ts

I can't see any of those changes in, am I'm doing something wrong?

**Comment by thetylerwolf** [comment]
Hey @Manny91, I didn't get a chance to reply until now. I think when you asked, the code had been merged into master, but the master code had not yet been released. As I mentioned, you could still use the functionality without the typings. Just put the `// @ts-ignore` comment above the code that throws a typescript error.

Regardless, it looks like there have been a few releases since then and my PR code was included in those releases, so updating should take care of it now.

**Pull request merged**
