### PR TITLE
Create a new folder for helm charts

### PR DESCRIPTION
**Pull request by rpaik**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

### CODE REVIEW

**Review by rchkv — APPROVED** [review]

**Comment by adnanrahic** [comment]
@hassankhan @igorlukanin @rpaik
Should we add an examples folder for regular K8s yaml files? We have a few examples for that we can add right away.

**Comment by rpaik** [comment]
> @hassankhan @igorlukanin @rpaik
> Should we add an examples folder for regular K8s yaml files? We have a few examples for that we can add right away.

Yeah, I'm all for it!

**Comment by adnanrahic** [comment]
@rpaik In that case we can add another folder eg. `examples/kubectl`. I'd be happy to add files there once this PR is merged.

**Comment by lvauvillier** [comment]
See #3277 
Tell me if I have to move the PR location.

**Review by adnanrahic — APPROVED** [review]

**Pull request merged**
