### PR TITLE
fix: QueryQueue - broken queuing on any error (TimeoutError: ResourceRequest timed out)

### PR DESCRIPTION
**Pull request by ovr**
Hello!

refs https://github.com/cube-js/cube.js/issues/2574

Thanks

### CODE REVIEW

**Comment by rongfengliang** [comment]
i do some load test this pr works. thanks !!!

**Comment by fabiosenracorrea** [comment]
@ovr hey! Thanks for this PR. I'm still experiencing broken queries with the 'Resource TImeout' issue. What should i do (open issue...)?

**Comment by rongfengliang** [comment]
> @ovr hey! Thanks for this PR. I'm still experiencing broken queries with the 'Resource TImeout' issue. What should i do (open issue..

sometime throw request timeout is ok,but if always will be a bug,this pr was to solve this problem

**Comment by fabiosenracorrea** [comment]
@rongfengliang i see. Yeah i investigate a little more on this issue before coming back here. But it was happening quite a lot after a while.

**Pull request merged**
