### PR TITLE
feat(@cubejs-backend/elasticsearch-driver): add a parameter to allow response formatting

### PR DESCRIPTION
**Pull request by vignesh-123**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[https://github.com/cube-js/cube.js/issues/986](https://github.com/cube-js/cube.js/issues/986)

I couldn't find any docs. Will create one in the next PR.

### CODE REVIEW

**Comment by paveltiunov** [comment]
Hey @vignesh-123 ! Could you please elaborate what this change does?

**Comment by vignesh-123** [comment]
It is a just a parameter to say elastic driver saying that it will receive a response from elastic as rows and columns or as the traditional JSON structure elastic provides

**Comment by vignesh-123** [comment]
You can find more on the issue here
[https://github.com/cube-js/cube.js/issues/986](url)

**Comment by rpaik** [comment]
@chadfaurie could you review this contribution for the Elasticsearch driver? 🙇

**Comment by rpaik** [comment]
👋 @vignesh-123 thanks for your contributions. I talked to the team and we will be making some changes to driver support so will go ahead and close this PR. Feel free to reach out to me if you have any questions 🙇

**Pull request closed without merging**
