### PR TITLE
add await when invoking schemaVersion

### PR DESCRIPTION
**Pull request by barakcoh**
**Check List**
- [X ] Tests has been run in packages where changes made if available
- [ X] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Add support for cases where `schemaVersion` needs to be `async`, e.g. fetching the version from remote storage

### CODE REVIEW

**Comment by paveltiunov** [comment]
@barakcoh Hey Barak! Just briefly checked code usage and it seems it probably not so easy as I thought before. `schemaVersion` property set in `CubejsServerCore.getCompilerApi()` and it isn't async. Good new is probably we can make it async.

**Comment by barakcoh** [comment]
hi @paveltiunov ! should I just add another `await` at https://github.com/cube-js/cube.js/blob/af07865ae2d3c11836ab5e01f17e97c3b2d5d662/packages/cubejs-server-core/core/index.js#L383?

**Comment by paveltiunov** [comment]
@barakcoh Yeah. Right. And make it `async`.

**Comment by paveltiunov** [comment]
@barakcoh Just checked usages more thoroughly and it seems we're safe to revert all changes to index.js as only `await` is in fact required. So your initial change was correct.

**Comment by barakcoh** [comment]
thanks @paveltiunov i'll push a reverse commit

**Pull request merged**
