### PR TITLE
Add SSL and unix socket support for mysql driver

### LINKED ISSUE #939: Add SSL and unix socket support for MySQL driver
**Is your feature request related to a problem? Please describe.**
To connect do a hosted mysql db I need ssl support, for testing I need unix socket support. The current mysql-driver doesn't have ssl and unix socket support.

**Describe the solution you'd like**
Since the library used to connect to the mysql db supports both requirements, it should be easy to add them by just reading the required environment variables from dotenv. The process should be quite similar to how it is solved in the postgres driver. If a socket is provided in dotenv, the host and port related variables should be ignored (this is also the default behavior of the mysql npm package. 

**Describe alternatives you've considered**
It might be possible to use something like ProxySQL to connect to remote mysql server, but the proposed solution would be much easier.

**Additional context**
I think I'll have some spare time this week and I will integrate this and add a PR.

### PR DESCRIPTION
**Pull request by davemaier**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [X] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [X] Docs have been added / updated if required

**Issue Reference this PR resolves**

Closes #939

### CODE REVIEW

**Comment by davemaier** [comment]
Somehow I can't manage to run any tests for the package successfully. Meaning that I also can't run the tests successfully with the unmodified code from the current master on upstream.

**Comment by ovr** [comment]
Hello @davemaier,

Thank you for contribution!

Tested & merged in `master`

**Comment by igorlukanin** [comment]
Hey @ovr, so this [issue](https://github.com/cube-js/cube.js/issues/939) is not needed anymore and should be closed as well, right?

**Comment by ovr** [comment]
@igorlukanin 

It should be closed, but we need to release a new version before closing the issue (which is more friendly).

**Pull request closed without merging**
