### PR TITLE
Rename 'Security' page to 'Authentication & Authorization'

### PR DESCRIPTION
**Pull request by hassankhan**
**Check List**
- [X] Tests has been run in packages where changes made if available
- [X] Linter has been run for changed code
- [X] Tests for the changes have been added if not covered yet
- [X] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Rename the 'Security' page as well as re-order it in the documentation. Also doing some minor fixes to the copy.

### CODE REVIEW

**Review by igorlukanin — APPROVED** [review]
👍

**Comment by keydunov** [comment]
@hassankhan does this commit changes the content of the guide or just moves under the new section for now?

**Comment by hassankhan** [comment]
@keydunov It does both, I can do it in separate PRs if you'd prefer?

**Review by keydunov — APPROVED** [review]

**Comment by keydunov** [comment]
@hassankhan :shipit:

**Pull request merged**
