### PR TITLE
feat: Include version in startup message

### PR DESCRIPTION
**Pull request by jcw-**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Includes the Cube.js version in the startup message:
image

The version is available in three places:

1. `CubejsServer.version()`
1. `CubejsServerCore.version()`
1. `const { version, port } = await cubejsServer.listen();`

### CODE REVIEW

**Comment by jcw-** [comment]
@paveltiunov curious what you think about doing something like this so the version is more discoverable (and also logged)? If this makes sense then I'll proceed to update the docs, examples, and guide content with the same change.

**Comment by paveltiunov** [comment]
@jcw- Hey Jc! I think it's good idea! It would be great to move this version retrieval to method of server instance.

**Comment by paveltiunov** [comment]
@jcw- Hey Jc! Looks good! We'd need just to resolve conflicts before merge.

**Comment by jcw-** [comment]
@paveltiunov conflicts resolved!

**Pull request merged**
