### PR TITLE
change playground urls to ralative urls

### PR DESCRIPTION
**Pull request by superbarne**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

I changed the urls for the playground api in to relative urls. Becaus i mounted the playground as express subapp and its wanted to call the playound from the root level.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@superbarne Hey Barne! Thanks for contributing this! Could you please elaborate a little bit more on your use case? Are you embedding Playground somewhere as part of your solution to be able to work with it in production environment?

**Comment by superbarne** [comment]
No not realy for production, its an internal tool. In my case i wanted to embed it in a litte express app, so i could access it directly for exploring the data.
I could also run it seperatly but i thougt it would be nice, if its in the same application.

**Comment by paveltiunov** [comment]
@superbarne That totally makes sense. Change seems good to me. The only thing is using relative paths isn't backward compatible at the moment because we know about deployments where playground served not at the root. I think we can go with base path solution. What do you think?

**Comment by superbarne** [comment]
and the base path configuration is passed via a configuration variable?

**Comment by paveltiunov** [comment]
@superbarne Yep. Right. Expose react app variable and rebuild playground with it: https://create-react-app.dev/docs/adding-custom-environment-variables.

**Comment by paveltiunov** [comment]
@superbarne We also just recently released new dashboard app which has the same Query builder as in Playground. Could you please check it and let us know if you still need to host Playground somewhere?

**Comment by paveltiunov** [comment]
@superbarne We just published https://react-dashboard.cube.dev/ which can solve this problem for you. Closing for now. Please reopen if you still need these changes.

**Pull request closed without merging**
