### PR TITLE
refactor(@cubejs-backend/schema-compiler): improve readability

### PR DESCRIPTION
**Pull request by Justin-ZS**
Hard to read without documents, so I refactor the big function into pieces.

### CODE REVIEW

**Comment by Justin-ZS** [comment]
@paveltiunov 
And I think we can merge the `isAdditive` branch to `leafMeasureAdditive` branch.
In `isAdditive` branch, `transformedQuery.measures` always equals `transformedQuery.leafMeasures`.

**Comment by paveltiunov** [comment]
@Justin-ZS Hey Jin! Thanks for refactoring this! Overall agree on that idea! However we'd need to test performance of this method very thoroughly. The reason for it there's high call throughput during `autoRollup` calculations. Like millions of calls. Current implementation is a base line: we should make it faster and not slower. So we want to be it both faster and more readable as a result of this change.

I'll write some performance tests which corresponds to real world load for this method and will get back to you on this.

**Comment by Justin-ZS** [comment]
@paveltiunov  Can't agree more for the importance of performance!
As a fan of Ramda too, I find if you write some code and expect it to obtain a very high performance, the first choice is not to use Ramda at all.
Immutability and functional style benefits to composing high-level logic, but poor at performance due to unoptimized JS engine.

**Comment by paveltiunov** [comment]
Closing as this code is out of date. Please feel free to open other PR to revisit the problem using a new codebase.

**Pull request closed without merging**
