### PR TITLE
docs(schema): ensure reference pages are under Reference section

### PR DESCRIPTION
**Pull request by hassankhan**
Story details: https://app.clubhouse.io/cube-dev/story/764

### CODE REVIEW

**Comment by keydunov** [comment]
Looks good. Are we handling old URLs with redirects?

**Comment by hassankhan** [comment]
@keydunov Yep we are, I went ahead and updated all the old URLs in the docs but all the old ones should work just fine 👍

**Comment by keydunov** [comment]
@hassankhan Can you please take care of the conflicts?

**Comment by keydunov** [comment]
@hassankhan can you resolve the conflict here please?

**Comment by hassankhan** [comment]
@keydunov Conflicts resolved 👍

**Pull request merged**
