### PR TITLE
feat(mssql-driver): add readonly aggregation for mssql sources

### PR DESCRIPTION
**Pull request by JoshMentzer**
**Description of Changes Made (if issue reference is not provided)**

Updating MSSqlDriver to implement downloadQueryResults function, enabling ability to have source systems use pre-aggregation where readOnly is true and externalDb utilized.

### CODE REVIEW

**Comment by jcw-** [comment]
@JoshMentzer Nice! I think you'll also need to implement `readOnly` on the driver, otherwise the base implementation that always returns `false` will be used - you can see #395 for an example of when this functionality was added to the Postgres driver.

**Comment by JoshMentzer** [comment]
@jcw- Got it, thx!

**Comment by jcw-** [comment]
@JoshMentzer what if you define your time dimension columns with explict SQL that does a conversion? https://cube.dev/docs/working-with-string-time-dimensions#top

**Comment by JoshMentzer** [comment]
> @JoshMentzer what if you define your time dimension columns with explict SQL that does a conversion? https://cube.dev/docs/working-with-string-time-dimensions#top

Sorry, I should have been more explicit - it's not the timeDimensions themselves, it's the timeDimension with granularity; the timeDimensions are datetime; so let's say there is one called closedAt - in the query for preaggregation it's coming back as closedAt_day.  That is the column that is being typed as nvarchar

**Comment by jcw-** [comment]
@JoshMentzer Oh I see - looks like that driver uses FORMAT for time dimension granularity, which turns it into a string: 

https://github.com/cube-js/cube.js/blob/846a519c99167459e8d3513150ebaaf0e11eb929/packages/cubejs-schema-compiler/adapter/MssqlQuery.js#L31-L39

While postgres uses `date_trunc` - looks like the `GRANULARITY_TO_INTERVAL` for mssql would be a good place to start!

**Comment by JoshMentzer** [comment]
@jcw- I think this is now good - thanks for the assist!

**Comment by JoshMentzer** [comment]
Is there something special to do to get the test-mssql to run locally?  I get 'ConnectionError: Login failed for user 'sa'' when attempting to run.  I have docker, and am able to run 'test' in the schema-compilor just not test-mssql

**Comment by jcw-** [comment]
@JoshMentzer I'm not sure - but when I run tests for say, the query-orchestrator, I use this command, maybe it will help:
```
yarn lerna run --concurrency 1 --ignore @cubejs-backend/jdbc-driver --scope @cubejs-backend/query-orchestrator test
```

**Comment by paveltiunov** [comment]
@JoshMentzer Hey Joshua! Looks good to me! Thanks for contributing it!

**Pull request merged**
