### PR TITLE
Added missing features to vue package

### LINKED ISSUE #32: Change dimension in the filter object in query to member
Name `dimension`  is misleading, since filter could be applied to both measures and dimensions. Support `dimension` key for the back compatibility.

### LINKED ISSUE #188: VueJs Client, limit not working
**Describe the bug**
When you try to perform a Limit on the query, que query builder, will not send the limit set to the backend. The vue client is not looking for that parameter to sent.

### PR DESCRIPTION
**Pull request by TCBroad**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

Fixes #32 (only for vue)
Fixes #188 

Adds some missing features to the vue package to bring it more in line with the documentation:
- Added support for measures in filters
- Added support for limit
- Added support for offset

I will add the remaining features in another PR as I didn't want this one to get too big

### CODE REVIEW

**Comment by paveltiunov** [comment]
Hey Tom! Thanks for providing this! It's really great! The only thing: is `dimension` -> `member` change backward compatible?

**Comment by TCBroad** [comment]
Good point - it isn't at the moment. I could add the old property back in and check both if you feel this is a suitable way forward?

**Comment by paveltiunov** [comment]
@TCBroad Yep. It would be great! Just revert changes to old tests and add checks for old properties with deprecated note. It would be enough. Thanks!

**Comment by paveltiunov** [comment]
@TCBroad Hey Tom! Do you have time to fix that this week? We can merge and fix it on your behalf if you aren't available this week.

**Comment by TCBroad** [comment]
@paveltiunov yeah no problem. I should be able to push some stuff later, I have the changes locally

**Comment by paveltiunov** [comment]
@TCBroad Looks great! Thanks for contributing this!

**Pull request merged**
