### PR TITLE
feat(gateway): Add GraphQL endpoint

### PR DESCRIPTION
**Pull request by lvauvillier**
This PR is an implementation of the GraphQL spec described in issue #3433

I think i covered all the main functionalities of the REST API.

## Description

A new endpoint `/cubejs-api/graphql` is added in the gateway.
All security middlewares (checkAuth, queryRewrite, etc.) are still used.

In dev mode, graphiql UI is available.

## How it works
- GraphQL schema is automatically generated using the compilerApi.
- GraphQL AST info are used to generate cubequery at root cube entity level
- Results are remapped to the graphql query shape

## Warning
Current implementation will raise an error for a `continueWait` response. Long polling is not implemented (and not possible with this API design).

## Example

original query:

```json
{
  "measures": ["Stories.count"],
  "dimensions": ["Stories.category"],
  "filters": [{
    "member": "Stories.isDraft",
    "operator": "equals",
    "values": ["No"]
  }],
  "timeDimensions": [{
    "dimension": "Stories.time",
    "dateRange": ["2015-01-01", "2015-12-31"],
    "granularity": "month"
  }],
  "limit": 100,
  "offset": 50,
  "order": {
    "Stories.time": "asc",
    "Stories.count": "desc"
  },
  "timezone": "America/Los_Angeles"
}
```

is equivalent to graphql query:
```graphql
{
  load(limit: 100, offset: 50, timezone: "America/Los_Angeles") {
    stories(granularity: {time: month}, orderBy: { time: asc, count: desc }, where: {isDraft: {equals: "NO"}, time: {inDateRange: ["2015-01-01", "2015-12-31"]}}) {
      count
      category
      time
    }
  }
}

```

directives `@skip` and `@include` are supported:

```graphql
query GetStories($byCategory: Boolean = false) {
  stories(granularity: { time: month }) {
      count
      category @include(if: $byCategory)
      time
  }
} 
```

### CODE REVIEW

**Comment by paveltiunov** [comment]
@lvauvillier On a side note how would query with members from multiple cubes look like?

**Comment by lvauvillier** [comment]
@paveltiunov I just push an update and it works nicely :)

The new filters works great with autocompletion and we can now join cubes.

Filters are autogenerated based on the member type with some changes from the REST API (heavily inspired from hasura and prisma filtering api):
- it accepts number values for number types (instead of string values everywhere)
- `notSet` is removed in favor of `{ set:  false }`
- `equals` and `notEquals` accept a single value, but we have now `in`and `notIn` for multiple values
- `AND` and `OR` fields for boolean operator
- filters can be set at `load` level or `<cubeName>` level. Using `load` level allow user to use boolean operator accros multiple cubes.

Example:
```graphql
{
  load(offset: 20, limit: 5, where: {users: {firstName: {notEquals: "Golden"}}}) {
    orders(granularity: {createdAt: day}, where: {OR: [{createdAt: {afterDate: "2021-01-01"}}, {status: {equals: "shipped"}}]}, orderBy: {createdAt: asc}) {
      count
      status
      createdAt
    }
    users {
      firstName
    }
  }
}
```
will generate:
```json
{
  "measures": [
    "Orders.count"
  ],
  "dimensions": [
    "Orders.status",
    "Users.firstName"
  ],
  "timeDimensions": [
    {
      "dimension": "Orders.createdAt",
      "granularity": "day"
    }
  ],
  "order": {
    "Orders.createdAt": "asc"
  },
  "limit": 5,
  "offset": 20,
  "filters": [
    {
      "member": "Users.firstName",
      "operator": "notEquals",
      "values": [
        "Golden"
      ]
    },
    {
      "or": [
        {
          "member": "Orders.createdAt",
          "operator": "afterDate",
          "values": [
            "2021-01-01"
          ]
        },
        {
          "member": "Orders.status",
          "operator": "equals",
          "values": [
            "shipped"
          ]
        }
      ]
    }
  ]
}
```

**Comment by paveltiunov** [comment]
@lvauvillier Looks really good and it seems to play nicely overall. What do you think about putting granularity inside the time dimension field like this?
```
{
  load(offset: 20, limit: 5, where: {users: {firstName: {notEquals: "Golden"}}}) {
    orders(where: {OR: [{createdAt: {afterDate: "2021-01-01"}}, {status: {equals: "shipped"}}]}, orderBy: {createdAt: asc}) {
      count
      status
      createdAt { day }
    }
    users {
      firstName
    }
  }
}
```
The reason for it is generally speaking you can query multiple granularities of the same time dimension. It's rare but still valid use case.

Could you please also rebase so we can run the test and be ready to merge?

**Comment by lvauvillier** [comment]
@paveltiunov If we add granularity subfields to time dimensions, we need to keep the ability use the time dimension without granularity.

We can add a new `raw` field to achieve this (i'm not sure of the name)

With granularity

```graphql
{
  load(offset: 20, limit: 5, where: {users: {firstName: {notEquals: "Golden"}}}) {
    orders(where: {OR: [{createdAt: {afterDate: "2021-01-01"}}, {status: {equals: "shipped"}}]}, orderBy: {createdAt: asc}) {
      count
      status
      createdAt {
        day
      }
    }
    users {
      firstName
    }
  }
}
```

Without granularity

```graphql
{
  load(offset: 20, limit: 5, where: {users: {firstName: {notEquals: "Golden"}}}) {
    orders(where: {OR: [{createdAt: {afterDate: "2021-01-01"}}, {status: {equals: "shipped"}}]}, orderBy: {createdAt: asc}) {
      count
      status
      createdAt {
        raw
      }
    }
    users {
      firstName
    }
  }
}
```

I also think about using a union type, but scalars are not allowed: we can't use a simple `DateTime | Granularity`.
Union types also require to use fragment notation in the query:
```graphql
createdAt {
  ...on Granularity {
    day
  }
}
```

**Comment by paveltiunov** [comment]
@lvauvillier Yeah. This is a really great point! `raw` might work. Other way is to have explicit dimensions resolver like this to avoid reserved names introduction:
```graphql
{
  load(offset: 20, limit: 5, where: {users: {firstName: {notEquals: "Golden"}}}) {
    orders(where: {OR: [{createdAt: {afterDate: "2021-01-01"}}, {status: {equals: "shipped"}}]}, orderBy: {createdAt: asc}) {
      count
      status
      dimensions {
        createdAt
      }
    }
    users {
      firstName
    }
  }
}
```

**Comment by paveltiunov** [comment]
@lvauvillier I guess we can go with `raw` for now and see how it progresses over time. Could you please add it? Thanks!

**Comment by lvauvillier** [comment]
@paveltiunov I just pushed a new version. I finally chose the name `value` instead of `raw`.
It now works with multiple granularities at the same time.

I also added the missing `quarter` granularity and add a nonNull constraint to all members.

New graphQL spec:

```graphql
input DateTimeFilter {
  afterDate: String
  beforeDate: String
  equals: String
  in: [String]
  inDateRange: [String]
  notEquals: String
  notIn: [String]
  notInDateRange: [String]
  set: Boolean
}

input FloatFilter {
  contains: Float
  equals: Float
  in: [Float]
  notContains: Float
  notEquals: Float
  notIn: [Float]
  set: Boolean
}

input StringFilter {
  contains: String
  equals: String
  in: [String]
  notContains: String
  notEquals: String
  notIn: [String]
  set: Boolean
}

type TimeDimension {
  day: DateTime!
  hour: DateTime!
  minute: DateTime!
  month: DateTime!
  quarter: DateTime!
  second: DateTime!
  value: DateTime!
  week: DateTime!
  year: DateTime!
}

enum OrderBy {
  asc
  desc
}

type Query {
  load(limit: Int, offset: Int, renewQuery: Boolean, timezone: String, where: RootWhereInput): [Result!]!
}

type Result {
  <cubeName>(orderBy: <CubeName>OrderByInput, where: <CubeName>WhereInput): <CubeName>Members!
  ...
}

type <CubeName>Members {
  <member>: String! | Float!
<timeMember>: TimeDimension!
  ...
}

input RootWhereInput {
  AND: [RootWhereInput!]
  OR: [RootWhereInput!]
  <cubeName>: <CubeName>WhereInput
  ...
}

input <CubeName>WhereInput {
  AND: [<CubeName>WhereInput!]
  OR: [<CubeName>WhereInput!]
  <member>: FloatFilter | DateTimeFilter | StringFilter
  ...
}

input <CubeName>OrderByInput {
 <member>: OrderBy
 ...
}
```

**Comment by paveltiunov** [comment]
@lvauvillier We're almost there! The small thing I noted is you introduced cache for the schema. If we cache it we should respect multi-tenancy. To not withhold merging of this big PR we can consider either removing caching (I realize it won't be suitable for production workload yet) or storing it as a part of `CompilerApi`. You can introduce a setter for that. Should be an easy fix.

**Comment by lvauvillier** [comment]
@paveltiunov Oh, you are right, schemas can de dynamic if a `repositoryFactory` is defined.

It also raises the point of extending graphiQL UI to add the ability to define security contexts like in the playground. This can be part of a new PR.

**Comment by paveltiunov** [comment]
@lvauvillier Hey Luc! Looks great! Thanks again for such a big effort!

**Pull request merged**
