### PR TITLE
support REDIS_PASSWORD env variable

### PR DESCRIPTION
**Pull request by lanphan**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**
As my Redis instance has password, I did add configuration for Redis here to support password.

[Description goes here]

### CODE REVIEW

**Comment by paveltiunov** [comment]
@lanphan Hey Lan! Overall looks great! Did you have a chance to test it without providing any env variables?

**Comment by lanphan** [comment]
Hi @paveltiunov pave,
Not yet ... let I check right now and let you know.

**Comment by lanphan** [comment]
Hi @paveltiunov ,
It works with configuration below:
1. docker-compose.yml starts official redis container:
```
    redis-test:
      image: redis:latest
      restart: unless-stopped
      networks:
        - backend
```

2. .env file of cubejs only with REDIS_URL:
```
REDIS_URL=redis://redis-test:6379/0
```

3. runs Playground ok, can query and display chart well.

**Comment by paveltiunov** [comment]
@lanphan Sounds great! Thanks again!

**Pull request merged**
