### PR TITLE
fix(@cubejs-schema-compiler): add parameter to groupByClause function to generate proper column identifiers in MSSQL subqueries

### PR DESCRIPTION
**Pull request by davefrancis**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

This PR resolves issue #573

**Description of Changes Made (if issue reference is not provided)**

These changes extend PR #591 and incorporate the suggests in that pull request to introduce a parameter in the `groupByClause()` function.

### CODE REVIEW

**Comment by rpaik** [comment]
@ovr can you help with the review?

**Comment by davefrancis** [comment]
Hey @rpaik, wondering if your team has had a chance to take a look at this one yet? Happy to make any required changes. Thanks again!

**Comment by ovr** [comment]
Hello @davefrancis ,

I am sorry for the late reply, we need at least one integration test for MSSQL in the schema-compiler to verify that it works and it will help us in the feature to not break it. Can you add a test for it?

Thanks

**Comment by davefrancis** [comment]
@ovr thanks for reviewing. I'll add a test or two and ping you when it's done.

**Comment by paveltiunov** [comment]
@davefrancis I'd introduce a separate method in `BaseQuery` for that. Something like `aggregateSubQueryGroupByClause`. This way we don't need to modify the method signature in every driver.

**Comment by davefrancis** [comment]
Resolved in #5078

**Pull request closed without merging**
