### PR TITLE
fixed clickhouse joins in cubejs-schema-compiler

### PR DESCRIPTION
**Pull request by antnmxmv**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

#3534

### CODE REVIEW

**Comment by paveltiunov** [comment]
@antnmxmv Hey Anton! Looks great! I believe it'd be beneficial to add a test for this use case.

**Comment by antnmxmv** [comment]
> @antnmxmv Hey Anton! Looks great! I believe it'd be beneficial to add a test for this use case.

Hi! Test for this usecase has been added already and there was the comment line saying that it crashes because of issue that this PR covers. But after I fixed the issue, test has started to fail because of timestamp type that is not contains time zone. So after I make sure, that query has been generated and expected result appeared (but time zone), I have changed the comment above this test.

**Comment by paveltiunov** [comment]
@antnmxmv Do you think you can fix the test and enable it? It would be really beneficial.

**Comment by antnmxmv** [comment]
@paveltiunov done.

**Comment by paveltiunov** [comment]
Hey @antnmxmv ! Looks good to me! Thanks for contributing it!

**Pull request merged**
