### PR TITLE
Add Crate support to Cube.js

### PR DESCRIPTION
**Pull request by robd003**
**Check List**
- [X] Tests has been run in packages where changes made if available
- [X] Linter has been run for changed code
- [X] Tests for the changes have been added if not covered yet
- [X] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Add support for [Crate](https://github.com/crate/crate) to Cube.js

### CODE REVIEW

**Comment by rpaik** [comment]
@robd003 I assume this is replacing https://github.com/cube-js/cube.js/pull/4471?

**Comment by robd003** [comment]
@rpaik correct

**Review by cristipp — COMMENTED** [review]
Looks great. packages/cubejs-crate-driver/test/CrateDriver.test.ts seems to have been lost from the previous PR? Can you please add it back?

**Comment by robd003** [comment]
@cristipp good catch!

**Comment by cristipp** [comment]
Quick note: The linter is unhappy about packages/cubejs-schema-compiler/src/adapter/CrateQuery.js Can you please run yarn lint in packages/cubejs-schema-compiler and fix the lint errors? Bonus, please fix the warnings too :slightly_smiling_face:

**Comment by cristipp** [comment]
Awesome. I'll review the rest of the PR in the meantime.

**Comment by cristipp** [comment]
Hi Robert, any news on this? Been sick for a little while, sorry for the hiatus.

**Comment by adnanrahic** [comment]
Closing as https://github.com/cube-js/cube.js/pull/4929 is merged.

**Pull request closed without merging**
