### PR TITLE
Update DruidQuery.ts

### PR DESCRIPTION
**Pull request by rongfengliang**
bugfix for support like https://github.com/cube-js/cube.js/issues/3109

### CODE REVIEW

**Comment by rongfengliang** [comment]
@ovr  thanks

**Comment by paveltiunov** [comment]
@rongfengliang Thanks for contributing it! Is there any chance you can add the simple test in `druid-driver.test.ts`?

**Comment by rongfengliang** [comment]
> @rongfengliang Thanks for contributing it! Is there any chance you can add the simple test in `druid-driver.test.ts`?

this is a query test so I create another test file `druid-query.test.ts`

**Comment by paveltiunov** [comment]
@rongfengliang It seems `LIKE` is case-sensitive. We probably should use `ICONTAINS_STRING` instead.

**Comment by rongfengliang** [comment]
> @rongfengliang It seems `LIKE` is case-sensitive. We probably should use `ICONTAINS_STRING` instead.

yes. from source code I seen  it use uppercase string so it should be works

**Comment by ovr** [comment]
Thank you @rongfengliang 👍  🍰 🥮

**Pull request merged**
