### PR TITLE
Update angular

### PR DESCRIPTION
**Pull request by ilyaryabchinski**
update angular to version 10

### CODE REVIEW

**Comment by ilyaryabchinski** [comment]
That's weird. Some issues with the database

**Comment by paveltiunov** [comment]
@ilyaryabchinski Hey Ilya! Oh. Wow! Looks great! Thanks for contributing it!

**Comment by ilyaryabchinski** [comment]
@paveltiunov thanks! But what was wrong with the PR so you reverted it? Did it became broken?

**Comment by paveltiunov** [comment]
@ilyaryabchinski Hit this button accidentally. PR looks good to me and it's already released. You can try it out in 0.19.54.

**Comment by ilyaryabchinski** [comment]
@paveltiunov Ok, I just got scared that I broke the package 😨 Anyway, thank you for your help 👍

**Pull request merged**
