### PR TITLE
Bump corejs

### PR DESCRIPTION
**Pull request by cemremengu**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

Try bumping corejs so we dont get the deprecation warning during install

### CODE REVIEW

**Comment by hassankhan** [comment]
@cemremengu Thanks for making the PR - I'd been meaning to since I was finding the deprecation warning annoying 😅

@pavel It may be an idea to use something like [Dependabot](https://dependabot.com/). It'll scan and create PRs for all available dependencies, and can even be configured to automerge PRs if all tests pass.

**Comment by cemremengu** [comment]
+1 for dependabot or any other tool that can make the global upgrades across the entire repo easier

**Comment by cemremengu** [comment]
I have had some nice experience with `greenkeeper` regarding this

**Comment by paveltiunov** [comment]
@hassankhan Thanks for suggestion! Just enabled Dependabot for the repo.

**Pull request merged**
