### PR TITLE
Fix graphql non capital cube name issue

### PR DESCRIPTION
**Pull request by MattFanto**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

Solves https://github.com/cube-js/cube.js/issues/5643

**Description of Changes Made (if issue reference is not provided)**

To avoid graphql schema issue when cube name is not capitalized (PascalCase) I added a function to normalize the cube config to PascalCase.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@MattFanto Thanks for contributing to this one! Could you please fix the linter errors?

**Comment by MattFanto** [comment]
Hi @paveltiunov thanks for checking I didn't notice the linter should be fixed now

**Comment by MattFanto** [comment]
Hi @paveltiunov thanks a million, good to know I removed the warning!

**Comment by MattFanto** [comment]
Hi @paveltiunov I would be happy to merge this PR just a +1 is missing

**Comment by paveltiunov** [comment]
@MattFanto I think we're good to go with the merge! You just need to rebase PR in order to resolve conflicts. Thanks for contributing!

**Comment by MattFanto** [comment]
Hi @paveltiunov great news you are welcome, I rebased my PR run test and lint and now should be ready to merge

**Pull request merged**
