### PR TITLE
Fix postgres datatype lookup

### PR DESCRIPTION
**Pull request by shietpas**
I incorporated the toLowerCase() on datatype for consistency and added datetime and integer datatypes.  Resolves Issue #176

### CODE REVIEW

**Comment by paveltiunov** [comment]
@shietpas Hey Scott! Thanks for providing this one! Could you please elaborate a little bit on `toLowerCase()` case? What's the case you need it?

**Comment by shietpas** [comment]
@paveltiunov When the external rollup (pre-aggregate) table is created, the data types came through as "STRING", "DATETIME", etc.  Since the key lookup in the GenericTypeToPostgres object is case sensitive, it did not find a match on data type "string" and therefore did not convert to "text".  Automatically converting to lowercase will support matching regardless of case.

**Comment by shietpas** [comment]
FYI, the scenario where this occurred is using PostgreSQL as External Rollup DB and Big Query as primary DB.  The Big Query data types are captured as uppercase.

**Comment by paveltiunov** [comment]
@shietpas Gotcha. I believe these types should be fixed at BigQuery side because DBs other than Postgres would be affected as well.

**Comment by paveltiunov** [comment]
@shietpas Do you think you can fix `BigQueryDriver` and `PostgresDriver` accordingly? Thanks!

**Pull request closed without merging**
