### PR TITLE
Preview Environments for Pull Requests by Uffizzi

### PR DESCRIPTION
**Pull request by ShrutiC-git**
**Check List**
- [X] Tests has been run in packages where changes made if available
- [X] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added/updated if required

**Issue Reference this PR resolves**
https://github.com/cube-js/cube.js/issues/5449

**Description of Changes Made (if issue reference is not provided)**
This PR is adding support for preview environments for PR events (opened, sync'ed, reopened, etc) powered by [Uffizzi](https://www.uffizzi.com/).

This PR is using GHA workflows to build and provision the preview environments. Utilizing docker-compose examples from Cube's repo, the PR uses docker-compose.uffizzi.yml to build Cube.JS from source - this makes sure the latest changes are reflected in the preview. The docker-compose also includes a MySQL instance to persist data.

Once a PR event is triggered — PR opened, PR synced, review requested — the build workflow will build the image, and the preview workflow will either spin up a new preview or update an existing preview. The previews are ephemeral — so they live for only as long as needed.

A comment will be posted on the PR containing the URL of the preview environment, allowing contributors and maintainers to easily navigate to the preview.

## How Has This Been Tested?
In order to test this, I have created a [PR](https://github.com/ShrutiC-git/cube.js/pull/7) against the main branch of my personal fork of Cube.JS. This triggered the workflow to create a new preview environment - [here](https://pr-7-deployment-8304-cube-js.app.uffizzi.com/) and this [comment](https://github.com/ShrutiC-git/cube.js/pull/7#issuecomment-1331722791), posted on the PR, takes me to the preview environment.

You can access this preview without needing to sign up/sign in.

Once you are logged in, you will see Cube.JS dashboard. This preview is pre-seeded with a Postgres instance, and as such, you will be able to generate schema through the `Generate Schema` tab on the navbar and further build graphs on the dashboard. 

To generate the schema, select the `public table` and click on `Generate Schema`. The objects for the Schema have been taken from Cube.JS example repos. You can now head to the dashboard to select your needed `measures` and `dimensions` to generate charts, corresponding SQL query, or React code. 

We use `nginx` for routing. Due to that, the dashboard is made available at `/dashboard-url` as opposed to `/#dashboard`. To view the dashboard, first, start the app from the `Dashboard` tab in the navbar, and then visit `/dashboard-url`. 

## Changes in the PR
This PR adds a  `Dockerfile` and a `docker-compose.uffizzi.yml` file which builds `Postgres`, `nginx`, and `Cube.JS`. This compose also has a Uffizzi-integration, which exposes an entry point into the application `(nginx-proxy` here). 

There are 2 GitHun actions added to this PR:
 1. uffizzi-build.yml (which, as the name suggests, builds the images)
 2. uffizzi-preview.yml (which either spinds up a new preview or updates an existing preview)

You can read more about the 2-stage workflow [here](https://www.uffizzi.com/preview-environments-guide/github-actions-two-stage-workflow). 
 
The PR has a DB seeding file for Postgres, and Schema files under the `Schema` folder, and a `Dashboard-app` is also added to the PR for testing. Along with that, there is also an `entrypoint.sh` script responsible for updating the mount point for the `Dashboard`. 

*********************

Looking forward to powering preview environments for Cube.JS, and thereby, making reviewing, testing, releasing easy. Please let me know if there're any changes required or if there's anything I can add to align this PR and Uffizzi with Cube's development efforts.

### CODE REVIEW

**Comment by igorlukanin** [comment]
@ShrutiC-git I appreciate the effort but I'm not sure how practical these preview environments are for Cube. @paveltiunov @buntarb WDYT?

**Comment by ShrutiC-git** [comment]
thanks, @igorlukanin ~ thanks for getting back. 
I'll be interested in making it as relevant as possible for Cube. Ultimately, this is for enhancing maintainer productivity and increasing release velocity. There could be a couple of ways Uffizzi could be used to support its purpose. 

If the team needs anything specific, let me know and I'll work something out.

**Comment by ShrutiC-git** [comment]
hi, @igorlukanin, hope you were able to investigate this. What are your thoughts? Let me know how can I help to make this valuable to Cube

**Comment by igorlukanin** [comment]
@ShrutiC-git I'm sorry, since this is not a priority, I wasn't able to make up my mind yet. I'll ping you when I do. Thank you!

**Comment by ShrutiC-git** [comment]
thanks for the update, @igorlukanin — that sounds good

**Comment by jpthurman** [comment]
Hi @paveltiunov - friendly ping here.  Would Uffizzi preview environments be helpful for cube.js in reducing PR review times?
Here's a few [projects](https://www.notion.so/uffizzi/bd10b5646a76470ab21e5793c3cd2ca6?v=f56d96c0fe75424fb56111aa2bfce4fb) that are using our Preview Environment solution.

If this wouldn't be valuable for your project we can close this out.

**Comment by ShrutiC-git** [comment]
Nothing heard - closing this PR

**Pull request closed without merging**
