### PR TITLE
docs(examples): move all recipes to Examples & Tutorials section

### PR DESCRIPTION
**Pull request by rchkv**
- created `Examples, Tutorials & Recipes` directory;
- moved Examples page to the new directory;
- added the first recipes: Active user, pagination.

### CODE REVIEW

**Comment by rchkv** [comment]
@igorlukanin @hassankhan what do you think about these recipe subcategories? How does it look like for you? :) 
Let me remind you that there will be a lot of recipes and the list may be large... 

Also, we have a bug. The menu list doesn't show all items from the last menu category `Examples & Tutorials`. If I zoom out the browser window, I'll see all items in the category `Examples & Tutorials`. Is it a known issue? I made it on my local machine, this PR needs more recipes to reproduce the issue.

Снимок экрана 2021-08-03 в 16 29 19

**Comment by hassankhan** [comment]
@rchkv I think we'll have to defer to @keydunov's judgement on this one 😀 

With regards to the bug, I can reproduce it by lowering my screen resolution. Will add it to the backlog, thanks for reporting 👍

**Comment by igorlukanin** [comment]
I accidentally marked it as "Ready for review" but what I really wanted — just to get a Netlify preview link. Sorry.

**Comment by igorlukanin** [comment]
Overall, I like this. Nice job, @rchkv!

* I think that "RECIPES / ANALYTICS" can be just "ANALYTICS" (no value in repeating "recipes" multiple times)
* I wonder if we can make recipe categories ("Analytics", "Queries", etc.) expand and collapse just like the top-level pages in the docs sidebar. It would help reduce the size of the recipe list in the sidebar
* I think that, in this PR, we might just move existing content to recipes so we can release it soon (and leave further changes like adding `<GitHubCodeBlock... >` and other stuff later

I'd love to see an updated version of this that we can ask @hassankhan and @keydunov to approve later today or tomorrow.

**Comment by rchkv** [comment]
@igorlukanin 

> I think that "RECIPES / ANALYTICS" can be just "ANALYTICS" (no value in repeating "recipes" multiple times)
I agree. Removed `RECIPIS`

>I wonder if we can make recipe categories ("Analytics", "Queries", etc.) expand and collapse just like the top-level pages in the docs sidebar. It would help reduce the size of the recipe list in the sidebar
Good point, but I'm not sure that we can do it (I need to deep in code for this). @hassankhan do you know how we can do it?

>I think that, in this PR, we might just move existing content to recipes so we can release it soon (and leave further changes like adding <GitHubCodeBlock... > and other stuff later
I moved all tutorials except those that @hassankhan will move to `Fundamentals` section, and those that we marked as `DONT DO THIS` in the [Recipe catalogue](https://www.notion.so/Recipe-Catalogue-2a3cea64fb4240af879a1da137864ed4). Do you think we need move it too?

Also, I have hidden the recipe pages that are not ready yet (active users, pagination).

**Comment by igorlukanin** [comment]
@rchkv 
> those that we marked as DONT DO THIS in the Recipe catalogue. Do you think we need move it too?
As long as we're not changing them (= spending time on them) but just moving to the new place—yep, let's do it!

**Review by keydunov — APPROVED** [review]

**Review by hassankhan — APPROVED** [review]

**Pull request merged**
