### PR TITLE
feat: add `CUBEJS_DB_PASSWORD` as alias for `CUBEJS_DB_PASS`

### PR DESCRIPTION
**Pull request by gokulanv**
… to process.env.CUBEJS_DB_PASS

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**
#733 
[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]
@vasilev-alex This is my first PR for CubeJs. Please validate and let me know the additional changes that I should make. If there are any tests to be run, please suggest me those as well.

### CODE REVIEW

**Comment by gokulanv** [comment]
Yes yes, I will update them once you approve if this is the format. Also, what would be the changes required in templates.js and templates.test.js?

**Comment by vasilev-alex** [comment]
> Yes yes, I will update them once you approve if this is the format. Also, what would be the changes required in templates.js and templates.test.js?

I think we can leave it as it is. `CUBEJS_DB_PASS` will be there by default but the drivers will accept both for convenience

**Comment by gokulanv** [comment]
@vasilev-alex  PR Updated.

**Comment by gokulanv** [comment]
@vasilev-alex That looks much better and cleaner.
Please tell me if the below changes look okay.

> packages/cubejs-server-core/core/index.js:535

```
static createDriver(dbType) {
    checkEnvForPlaceholders();
    const dbConfig = {
      host: process.env.CUBEJS_DB_HOST,
      database: process.env.CUBEJS_DB_NAME,
      port: process.env.CUBEJS_DB_PORT,
      user: process.env.CUBEJS_DB_USER,
      password: process.env.CUBEJS_DB_PASS || process.env.CUBEJS_DB_PASSWORD
    }
    return new (CubejsServerCore.lookupDriverClass(dbType))(dbConfig);
  }

```

> packages\cubejs-mysql-driver\driver\MySqlDriver.js:12

```
class MySqlDriver extends BaseDriver {
  constructor(config) {
    super();
    const { pool, ...restConfig } = config || {};
    this.config = {
      config,
      ...restConfig
    };
```

**Comment by vasilev-alex** [comment]
Let's for now only refactor the config for `password`.

```js
  static createDriver(dbType) {
    checkEnvForPlaceholders();
    
    const config = {
      password: process.env.CUBEJS_DB_PASS || process.env.CUBEJS_DB_PASSWORD
    };
    
    return new (CubejsServerCore.lookupDriverClass(dbType))(config);
  }
```

**Comment by vasilev-alex** [comment]
Closing due to inactivity

**Pull request closed without merging**
