### PR TITLE
docs: merge `docs/` and `docs-build/`

### PR DESCRIPTION
**Pull request by hassankhan**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Merging the `docs/` and `docs-build/` folders. Also updated paths in CI where appropriate.

### CODE REVIEW

**Review by igorlukanin — APPROVED** [review]

**Comment by igorlukanin** [comment]
@hassankhan, I'm good with the changes 👍 

However, I wonder if it would make more sense to move `/docs-build` under `/docs/build` rather than moving `/docs` to `/docs/content`. It's extremely subjective, but IMO the actual content is more important than the docs build code, so we might try to have the content as close to the repo root as possible. WDYT?

**Comment by hassankhan** [comment]
@igorlukanin Thanks for the feedback. There are a few reasons why we did it this way:

1. Moving to `docs/build/` would create complications for #1177
2. The 'Edit Page' links in the static docs will point to the right place, so no loss of access there
3. We want `docs/` to be a Node package so we can add tooling like Markdownlint etc., without having to make the textual content a separate Node package.

**Comment by igorlukanin** [comment]
@hassankhan, thanks for the explanation! Totally makes so much sense!

**Review by ovr — APPROVED** [review]
LGTM

**Pull request merged**
