### PR TITLE
add connection release after execute query in OracleDriver

### PR DESCRIPTION
**Pull request by jay-choe**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

I got some issues when testing Oracle db. After debugging and found the queue (in connection pool) was full after some requests and at that time, i can not query to Oracle because there was no connections.

As [node-oracledb docs](https://oracle.github.io/node-oracledb/doc/api.html#connpooling) says
> Connections from the pool are obtained with [pool.getConnection()](https://oracle.github.io/node-oracledb/doc/api.html#getconnectionpool). If all connections in a pool are being used, then subsequent getConnection() calls will be put in a [queue](https://oracle.github.io/node-oracledb/doc/api.html#connpoolqueue) until a connection is available. Connections must be released with [connection.close()](https://oracle.github.io/node-oracledb/doc/api.html#connectionclose) when no longer needed so they can be reused. Make sure to release connections in all codes paths, include error handlers.

after use connection then call `connection.close()` for returning to pool. So, i added "returing to pool" code and tested it again and the problem solved.

Correct me if i am wrong or if i have to do something just let me know. Thanks.

### CODE REVIEW

**Comment by paveltiunov** [comment]
Hey @jay-choe ! Thanks for the contribution! Could you please add a smoke E2E test for the oracle driver as part of this PR? Oracle is community supported driver, and it'd be really helpful if we have it covered at least by some basic tests. You can use materialize driver as an example: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-testing/test/smoke-materialize.test.ts.

**Comment by jay-choe** [comment]
Okay i will try it.

**Comment by jay-choe** [comment]
@paveltiunov
It’s been a long time. I have been really busy.
I have added smoke test with my co-workers. (Cause I am not familiar with node.js)
Review plz and check if it fits in your team’s taste.
Also, if I have to resolve conflict or do something just let me know.
Thanks.

**Comment by paveltiunov** [comment]
@jay-choe Great! Could you please rebase your PR so we can run the tests? Thanks!

**Comment by jay-choe** [comment]
@paveltiunov Thanks for review and rebase it.
I guess there is a possible issue. As node module oracledb doesn't have a client used to connect db in it's module,  it needs oracle client which depends on OS. But I didn't add it and don't know it should be added in git repo.
Anyway check it plz and let me know if there is anything wrong thanks!

**Comment by jay-choe** [comment]
@paveltiunov any update?

**Comment by ovr** [comment]
@jay-choe Thanks for the contribution! 🍰

**Pull request merged**
