### PR TITLE
Moving to netlify

### PR DESCRIPTION
**Pull request by YakovlevCoded**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

### CODE REVIEW

**Review by igorlukanin — APPROVED** [review]
Wow! Great job, @YakovlevCoded 🤟

**Comment by YakovlevCoded** [comment]
@hassankhan Hi, in this PR I changed links in docs: https://github.com/cube-js/cube.js/blob/moving-to-netlify/docs/Examples.md. Review, please🙂

**Review by igorlukanin — APPROVED** [review]
It's a super huge update, but everything looks reasonable to me. Let's merge it for the good :smile:

**Comment by igorlukanin** [comment]
@hassankhan I think we should be good to merge this. Just want you to take note that @YakovlevCoded has updated the Examples page in the docs.

**Review by ovr — APPROVED** [review]
LGTM

**Review by hassankhan — APPROVED** [review]

**Comment by hassankhan** [comment]
Hi @YakovlevCoded @igorlukanin, sorry for the delay, this one slipped my radar 😅

**Pull request merged**
