### PR TITLE
fix: SQL Server case-sensitive collation support

### PR DESCRIPTION
**Pull request by rminelli**
**Check List**
- [ x] Tests has been run in packages where changes made if available
- [ x] Linter has been run for changed code
- [ x] Tests for the changes have been added if not covered yet
- [ x] Docs have been added / updated if required

**Issue Reference this PR resolves**

**Description of Changes Made (if issue reference is not provided)**
Fixed database query syntax for MS-SQL

### CODE REVIEW

**Comment by paveltiunov** [comment]
@rminelli Hey Roberto! Thanks for contributing this one! Could you please share which MS SQL version you use?

**Comment by rminelli** [comment]
@paveltiunov Hi Pavel! 
Of course.
This is the version I'm using: 
Microsoft SQL Server 2016 (SP1-GDR) (KB4458842) - 13.0.4224.16 (X64)   Aug 18 2018 09:00:06   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by paveltiunov** [comment]
@rminelli Got it. I believe it's because of your DB is in case-sensitive collation. I think we can override MS SQL driver to use uppercase names. We can't modify BaseDriver though because not all DB use uppercase table names for information schema. Could you please modify your PR accordingly?

Also it would be great if you can write test for MS SQL driver for these changes. Here's an example test for ClickHouseDriver: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-clickhouse-driver/test/ClickHouseDriverTest.js

**Comment by rminelli** [comment]
@paveltiunov Got it. 
Perfect, I'll do it :)
I will do the necessary tests as well.

**Comment by paveltiunov** [comment]
@rminelli Hey Roberto! Recent changes looks great! Are you going to provide overrides for other methods and tests? Thanks!

**Comment by rminelli** [comment]
@paveltiunov Hi Pavel! 
I will, but I would like to do it in another branch because it should take a little longer, all right for you?

**Comment by paveltiunov** [comment]
@rminelli Sounds good! But please use the same PR to add changes so we can track everything here.

**Comment by rminelli** [comment]
@paveltiunov perfect, I will do that.

**Comment by paveltiunov** [comment]
@rminelli Hey Roberto! Are you still working on this one?

**Comment by rminelli** [comment]
@paveltiunov Hey Pavel!
Yes, I'm still working, but due to the demands of work I couldn't devote so much time to it, but soon I will publish.

**Comment by paveltiunov** [comment]
Sounds good! Thanks!

**Pull request closed without merging**
