### PR TITLE
feat(@cubejs-backend/elasticsearch-driver): add cursor support to ElasticSearch driver

### PR DESCRIPTION
**Pull request by Vigneshg98**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

This change has been made to add the cursor logic in the Elastic Search driver. It will help us in getting the next set of records with the help of a cursor key returning in the previous response. The LIMIT value sent in the query is set as the fetch_size to get that many records from the elastic index.

**References**

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-format.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-pagination.html

**Looking Forward**

It would be more helpful if you could make the LIMIT value accept String. So that we could set the limit to ALL in the query and get the records by having a feasible fetch_size.

**Expected changes**

File path -> @cubejs-backend\api-gateway\index.js
limit: Joi.number().integer().min(1).max(50000)   (_existing_)
limit: Joi.string()

File path -> cubejs-schema-compiler\adapter\BaseQuery.js
const limitClause = this.rowLimit === null ? '' : ` LIMIT ${this.rowLimit && parseInt(this.rowLimit, 10) || 10000}`   (_existing_)
const limitClause = this.rowLimit === null ? '' : ` LIMIT ${this.rowLimit && this.rowLimit || 10000}`;

### CODE REVIEW

**Comment by rpaik** [comment]
@chadfaurie could you review this contribution for the Elasticsearch driver? 🙇

**Comment by rpaik** [comment]
> Hey @rpaik I not worked on the Elasticsearch drivers for CubeJs for quite some time due to work constraints, can you maybe @ the maintainers of the repo to assist?

Got it, thanks for getting back @chadfaurie

**Comment by rpaik** [comment]
Hi @Vigneshg98 thanks for your contributions. I talked to the team and we will be making some changes to driver support so we will close this PR for now. Feel free to reach out to me with any questions 🙇

**Comment by Vigneshg98** [comment]
@rpaik Sure, glad that the team would help us more on the elastic driver. Looking forward to contributing more to the development.

**Pull request closed without merging**
