### PR TITLE
docs: permissions and airflow integrations

### PR DESCRIPTION
**Pull request by buntarb**
**Check List**
- [x] Docs have been added / updated if required

### CODE REVIEW

**Review by paco-valdez — APPROVED** [review]
LGTM

**Comment by keydunov** [comment]
@buntarb Hold off merging this please; I'm still reviewing.

**Review by paco-valdez — CHANGES_REQUESTED** [review]
Can you update `contextToPermissions` to the new name please?

**Review by paco-valdez — APPROVED** [review]
LGTM

**Pull request closed without merging**
