### PR TITLE
fix: ISSUE-5528 prestodb - replace double escaping in contain filter

### PR DESCRIPTION
**Pull request by yuraborue**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

[ISSUE-5528](https://github.com/cube-js/cube.js/issues/5528)

**Description of Changes Made (if issue reference is not provided)**

Same with AthenaDriver hack

### CODE REVIEW

**Comment by paveltiunov** [comment]
Hey @yuraborue ! Thanks for contributing to this one! We'd really appreciate it if you can add the Presto E2E test, which tests this stuff. Example can be found here: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-testing/test/smoke-materialize.test.ts

**Comment by yuraborue** [comment]
Hi @paveltiunov ! I've added tests, could you review?

**Comment by paveltiunov** [comment]
@yuraborue Great! Could you please add the test to the `integration-smoke` action? Thanks!

**Comment by yuraborue** [comment]
@paveltiunov done! 
btw - `Build / Build & Test :dev for Debian without pushing (pull_request)` looks flaky, was red on first try and green after restart

**Review by epsyan — APPROVED** [review]

**Comment by paveltiunov** [comment]
@yuraborue Looks great! Thanks! Yep. We need more bulletproof cleanup for this E2E test.

**Pull request merged**
