### PR TITLE
Allow usage of CUBEJS_DB_SSL_CA parameter in postgres Driver.

### LINKED ISSUE #579: Support usage of CUBEJS_SSL_CA parameter for postgres Driver
**Is your feature request related to a problem? Please describe.**
Amazon RDS has released its 2019-2024 CA’s. The users must upgrade their CA’s to the new one before February 5th 2020. This is easily possilbe by setting the CA property in the SSL options of the database connection. Unfortunately the CUBEJS_SSL_CA parameter is not utilized in the postgres Driver.

**Describe the solution you'd like**
All the Environment variable regarding SSL connections should be utilized in the Driver.

**Describe alternatives you've considered**
Currently I am using a local modified copy of the driver passed in to the DriverFactory which works well.

### PR DESCRIPTION
**Pull request by gauravlanjekar**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

[fixes #579]

**Description of Changes Made (if issue reference is not provided)**

Copied over SSL code from MongoBI Driver. Assumed CUBEJS_DB_SSL_CA will be a filename. Updated the docs with this info.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@gauravlanjekar Hey Gaurav! Overall looks good to me. Can we remove `readFileSync()` and just stick with same approach used in `MongoBIDriver`? Seems to be more generic to me. Also could you please fix linter errors? Thanks!

**Comment by paveltiunov** [comment]
@gauravlanjekar Hey Gaurav! Looks great! Thanks for providing this!

**Comment by jcw-** [comment]
@gauravlanjekar 
> Assumed CUBEJS_DB_SSL_CA will be a filename

how is the new CUBEJS_DB_SSL_CA intended to be used? it doesn’t seem to work if I put in the relative path to the .pem file, is it intended to contain the actual file contents?

**Comment by gauravlanjekar** [comment]
Hi @jcw- The idea before was to use this parameter as a file name. but to keep the consistency with the Mongo driver we decided to have it as actual contents of the file. 
@jcw- may be you could create a separate issue to support file based certificate parameter
@paveltiunov what do you think ?

**Comment by paveltiunov** [comment]
@gauravlanjekar @jcw- Yeah. I think it makes sense to extract SSL code to BaseDriver and support file env variables as well in centralized manner.

**Comment by jcw-** [comment]
Sounds good, I'll make a separate issue - Heroku limits the total bytes of env var key-value-pairs and putting the pem in this env var exceeds the total size allowed, so the filename approach will provide Heroku support.

**Pull request merged**
