### PR TITLE
feat(@cubejs-backend/prestodb-driver): Added timezone support for queries.

### PR DESCRIPTION
**Pull request by d4rth-v4d3r**
Added an option to delegate timezone handling to Presto Client.

**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

I added an option to pass timezone directly to Presto Client.

This change will allow to delegate date time display handling directly to Presto.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@d4rth-v4d3r Hey Julián! Thanks for contributing this! Could you please elaborate on your use case? Especially what data schema you use and what results you expect?

**Comment by d4rth-v4d3r** [comment]
Hi @paveltiunov this is an explanation of this use case.

I have a database in MongoDb with this data (this is a projection):

```
/* 1 */
{
    "_id" : ObjectId("5eac75e18cd4d4001c7eec09"),
    "docDate" : ISODate("2020-05-01T17:15:34.978Z")
}
```  

If I use PrestoSQL to connect with MongoDb and use this data schema:

```
docdate: {
   sql: `${CUBE}.docdate`,
   type: `time`,
},
docdate_hour: {
    sql: `hour(${CUBE}.docdate)`,
    type: `number`,
},
docdate_minute: {
    sql: `minute(${CUBE}.docdate)`,
    type: `number`,
},
```

Using a query like this:

```
{
  "measures": [
    "VWAnalyticssaleorder.count"
  ],
  "timeDimensions": [
    {
      "dimension": "VWAnalyticssaleorder.docdate",
      "dateRange": "This month"
    }
  ],
  "dimensions": [
    "VWAnalyticssaleorder.docdate",
    "VWAnalyticssaleorder.docdate_hour",
    "VWAnalyticssaleorder.docdate_minute"
  ],
  "timezone": "America/Guatemala",
  "filters": []
}
```

I get this result:

```
{
    "VWAnalyticssaleorder.docdate": "2020-05-01T17:15:34.978",
    "VWAnalyticssaleorder.docdate_hour": 17,
    "VWAnalyticssaleorder.docdate_minute": 15,
    "VWAnalyticssaleorder.count": 3
},
```

Which is wrong, because this datetime in `America/Guatemala` should be `2020-05-01T11:15:34.978-06:00`, so hour must be 11 not 17. In documentation it says that we need to use `SQL_UTILS.convertTz`. If I change this is my schema:

```
docdate: {
  sql: SQL_UTILS.convertTz(`${CUBE}.docdate`),
  type: `time`,
},
docdate_hour: {
  sql: `hour(${SQL_UTILS.convertTz(`${CUBE}.docdate`)})`,
  type: `number`,
},
docdate_minute: {
  sql: `minute(${SQL_UTILS.convertTz(`${CUBE}.docdate`)})`,
  type: `number`,
},
```

And executing the same query as before I get this result:

```
{
    "VWAnalyticssaleorder.docdate": "2020-05-01T11:15:34.978",
    "VWAnalyticssaleorder.docdate_hour": 11,
    "VWAnalyticssaleorder.docdate_minute": 15,
    "VWAnalyticssaleorder.count": 3
},
```

This data is correct, but let's see the explain plain for both queries:

1. Query without timezone handling:
```
CPU: 77.46ms, Scheduled: 339.79ms, Input: 184 rows (1.61MB); per task: avg.: 184.00 std.dev.: 0.00, Output: 66 rows (2.90kB)
    Output layout: [hour, minute, docdate, count_270, $hashvalue_272]
    Output partitioning: HASH [hour, minute, docdate][$hashvalue_272]
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Aggregate(PARTIAL)[hour, minute, docdate][$hashvalue_272]
    │   Layout: [hour:bigint, minute:bigint, docdate:timestamp, $hashvalue_272:bigint, count_270:bigint]
    │   CPU: 6.00ms (4.72%), Scheduled: 10.00ms (2.19%), Output: 66 rows (2.90kB)
    │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
    │   count_270 := count("_id")
    └─ Project[]
       │   Layout: [docdate:timestamp, hour:bigint, minute:bigint, _id:ObjectId, $hashvalue_272:bigint]
       │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
       │   CPU: 7.00ms (5.51%), Scheduled: 9.00ms (1.97%), Output: 168 rows (8.70kB)
       │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
       │   $hashvalue_272 := combine_hash(combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("hour"), 0)), COALESCE("$operator$hash_code"("minute"), 0)), COALESCE("$operator$hash_code"("docdate"), 0))
       └─ Project[]
          │   Layout: [docdate:timestamp, hour:bigint, minute:bigint, _id:ObjectId]
          │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
          │   CPU: 7.00ms (5.51%), Scheduled: 13.00ms (2.84%), Output: 168 rows (7.22kB)
          │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
          │   hour := hour("docdate")
          │   minute := minute("docdate")
```

2. Query with timezone handling:
```
CPU: 63.13ms, Scheduled: 270.55ms, Input: 556 rows (1.81MB); per task: avg.: 556.00 std.dev.: 0.00, Output: 66 rows (2.90kB)
    Output layout: [expr_250, hour, minute, count_270, $hashvalue_272]
    Output partitioning: HASH [expr_250, hour, minute][$hashvalue_272]
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Aggregate(PARTIAL)[expr_250, hour, minute][$hashvalue_272]
    │   Layout: [expr_250:timestamp, hour:bigint, minute:bigint, $hashvalue_272:bigint, count_270:bigint]
    │   CPU: 1.00ms (0.65%), Scheduled: 3.00ms (0.51%), Output: 66 rows (2.90kB)
    │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
    │   count_270 := count("_id")
    └─ Project[]
       │   Layout: [expr_250:timestamp, hour:bigint, minute:bigint, _id:ObjectId, $hashvalue_272:bigint]
       │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
       │   CPU: 1.00ms (0.65%), Scheduled: 25.00ms (4.22%), Output: 168 rows (8.70kB)
       │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
       │   $hashvalue_272 := combine_hash(combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("expr_250"), 0)), COALESCE("$operator$hash_code"("hour"), 0)), COALESCE("$operator$hash_code"("minute"), 0))
       └─ Project[]
          │   Layout: [expr_250:timestamp, hour:bigint, minute:bigint, _id:ObjectId]
          │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
          │   CPU: 2.00ms (1.29%), Scheduled: 6.00ms (1.01%), Output: 168 rows (7.22kB)
          │   Input avg.: 168.00 rows, Input std.dev.: 0.00%
          │   expr_250 := CAST(date_add('minute', timezone_minute(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), date_add('hour', timezone_hour(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala'))) AS timestamp)
          │   hour := hour(CAST(date_add('minute', timezone_minute(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), date_add('hour', timezone_hour(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala'))) AS timestamp))
          │   minute := minute(CAST(date_add('minute', timezone_minute(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), date_add('hour', timezone_hour(at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala')), at_timezone(CAST("docdate" AS timestamp with time zone), 'America/Guatemala'))) AS timestamp))
```

The difference in query plan is clear, without any function Presto can delegate query to MongoDb using a raw date (allowing to use indexes, as a result better query performance), but with functions then Presto can not take advantages of this. 

With the change proposed with this pull request, we can configura Presto driver like this:

```
return new PrestoDb({
  schema: process.env.CUBEJS_DB_NAME,
  timezone: "America/Guatemala",
});
```

If we run the first query with this configuration, we can delegate date handling to Presto client directly and results are as expected:

```
{
    "VWAnalyticssaleorder.docdate": "2020-05-01T11:15:34.978",
    "VWAnalyticssaleorder.docdate_hour": 11,
    "VWAnalyticssaleorder.docdate_minute": 15,
    "VWAnalyticssaleorder.count": 3
},
```

Why? because `presto-client` can handle timezones in query execution to display dates in that format. 

I think it is a good idea to let the developer choose the best configuration and keeping in mind that huge data sets can impact performance.

Thanks.

**Comment by paveltiunov** [comment]
@d4rth-v4d3r I see. Could you please provide an example where **Query with timezone handling** slower than **Query without timezone handling**. In your example it's basically faster. Also did you have a chance to try
```
{
  "measures": [
    "VWAnalyticssaleorder.count"
  ],
  "timeDimensions": [
    {
      "dimension": "VWAnalyticssaleorder.docdate",
      "dateRange": "This month",
      "granularity": "hour"
    }
  ],
  "timezone": "America/Guatemala",
  "filters": []
}
```
It might solve your issue as well.

In regards to the change: I think it's helpful. However if we'll allow to define timezone on a driver level we'd need to correlate it somehow with a client side timezone. We have such code in some drivers which define storage timezone which can be different from UTC. These changes require corresponding part in dialect then. Please see MySQL driver and dialect for example:
https://github.com/cube-js/cube.js/blob/be42298801fb8f3d7ce49e109538f3fa4d3391c6/packages/cubejs-schema-compiler/adapter/MysqlQuery.js#L28
https://github.com/cube-js/cube.js/blob/51d1214caf95f4604ca8edc1b4a97a40a71870c1/packages/cubejs-mysql-driver/driver/MySqlDriver.js#L110

**Comment by d4rth-v4d3r** [comment]
Hi @paveltiunov I read the code and made some tests, but I think my use case is very specific because PrestoDb client does not have a global timezone handlig, it is per request and I was not able to get the db configuration in PrestoQuery, or env variables. My decision was to release a version of this driver for my use case. 

For me it works if driver has configured a timezone and is equal to query timezone. Currently PrestoDb Mongo Connector does not have support for timezones, so I think it could be related to this.

**Pull request closed without merging**
